- hosts: "ManagedNode"
  tasks:
   - name: "Yum Config"
     yum_repository: 
        name: "docker"
        description: "Docker Repository"
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
        gpgcheck: "no"
   - name: "Installing Docker"
     package: 
        name: "docker-ce-18.09.9-3.el7.x86_64"
        state: present
   - name: "Starting the service"
     service:
        name: "docker"
        state: started
        enabled: yes
   - name: "Copying file in folder"
     file:
       path: "/webpages"
       state: directory
   - name: "Copy the webpages to folder"
     copy: 
        src: "index.html"
        dest: "/webpages/"
   - name: "Python"
     command: "pip3 install docker"
   - name: "Launching Container"
     docker_container:
        name: "AnsibleContainer"
        image: "httpd"
        state: started
        exposed_ports:
        - "80"
        ports:
        - "8090:80"
        volumes:
        - /webpages:/usr/local/apache2/htdocs/
